[package]
name = "secret-toolkit-incubator"
version = "0.3.1"
edition = "2018"
authors = ["SCRT Labs <info@scrtlabs.com>"]
license-file = "../../LICENSE"
repository = "https://github.com/scrtlabs/secret-toolkit"
readme = "Readme.md"
description = "Experimental tools for writing Secret Contracts"
categories = ["cryptography::cryptocurrencies", "wasm"]
keywords = ["secret-network", "secret-contracts", "secret-toolkit"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
serde = { version = "1.0", optional = true }
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret", optional = true }
cosmwasm-storage = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret", optional = true }
secret-toolkit-serialization = { version = "0.3", path = "../serialization", optional = true }

[features]
default = ["cashmap",  "generational-store", "maxheap"]
cashmap = ["cosmwasm-storage", "serde", "secret-toolkit-serialization", "cosmwasm-std"]
generational-store = ["secret-toolkit-serialization", "serde", "cosmwasm-std"]
maxheap = ["secret-toolkit-serialization", "serde", "cosmwasm-std"]
